In [52]:
import numpy as np
import pandas as pd
import random

In [77]:
np.random.seed(42)
A=np.random.randint(0,6,(3,3))
print(A)

[[3 4 2]
 [4 4 1]
 [2 2 2]]


In [78]:
np.random.seed(42)
B=np.random.randint(0,8,(3,3))
print(B)

[[6 3 4]
 [6 2 7]
 [4 4 6]]


In [74]:
matrix_mul = np.dot(A,B)
print(matrix_mul)

[[50 25 52]
 [52 24 50]
 [32 18 34]]


In [75]:
matrix_mul = np.dot(B,A)
print(matrix_mul)

[[38 44 23]
 [40 46 28]
 [40 44 24]]


Вывод:  A*B!=B*A

In [80]:
C=np.array([[1, 2],[3, 4]])
print(C)
# в дз стоит обозначение матрицы "А". Я обозначил С , т.к в первой части уже присвоил "А" массиву 

[[1 2]
 [3 4]]


In [71]:
b=np.array([1, 2])
print(b)

[1 2]


При умножении матрицы на вектор-строку, умножаемая матрица может быть только вектором-столбцом, причем количество строк в векторе-столбце должно совпадать с количеством столбцов в векторе-строке.

In [97]:
matrix_mul=np.dot(C,b)
print(matrix_mul)

[ 7 10]


P.s. Прочитал, загуглив много статей, везде пишут про размерность. Был вариант ,что сделать первым аргументов -вектор и умножить на второй аргумент0 матрицу. ЕСЛИ МОЖНО НЕБОЛЬШОЙ ФИДБЭК ПО ЭТОМУ ВОПРОСУ ДЛЯ УСВОЕНИЯ МАТЕРИАЛА 